import { PromptTemplate } from '../types';

export const DEFAULT_PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: 'p1',
    title: 'Synthesize Data',
    description: 'Turn my meeting notes into 5 key bullet points for the team',
    category: 'Productivity',
    prompt: 'Please synthesize the following meeting notes into 5 clear, high-impact bullet points with designated action items and timelines:\n\n[Paste notes here]',
    icon: 'clock',
  },
  {
    id: 'p2',
    title: 'Creative Brainstorm',
    description: 'Generate 3 taglines for a new sustainable fashion brand',
    category: 'Creative',
    prompt: 'Generate 3 compelling, memorable taglines for a modern sustainable fashion brand. For each, provide a brief rationale on its psychological resonance with eco-conscious consumers.',
    icon: 'lightbulb',
  },
  {
    id: 'p3',
    title: 'Check Facts',
    description: 'Compare key differences between GDPR and CCPA',
    category: 'Research',
    prompt: 'Provide a structured comparison between GDPR (Europe) and CCPA (California). Highlight scope of applicability, consumer rights, penalty structures, and key compliance mandates for tech platforms.',
    icon: 'gavel',
  },
  {
    id: 'p4',
    title: 'Vision & Architecture OCR',
    description: 'Extract and analyze system architecture diagrams or UI screenshots',
    category: 'Coding',
    prompt: 'Please analyze this uploaded diagram or screenshot: 1) Identify key components and data flows, 2) Highlight potential bottlenecks or security risks, 3) Suggest architectural optimizations.',
    icon: 'camera',
    isVisionPrompt: true,
  },
  {
    id: 'p5',
    title: 'Sprint Execution Matrix',
    description: 'Create a detailed 7-day sprint plan for product launch',
    category: 'Productivity',
    prompt: 'Create a detailed 7-day sprint plan for a software product launch. Outline day-by-day objectives, critical path deliverables, QA milestones, and risk mitigations.',
    icon: 'layers',
  },
  {
    id: 'p6',
    title: 'Executive Stakeholder Brief',
    description: 'Draft a concise email to stakeholder on sprint progress',
    category: 'Writing',
    prompt: 'Draft a concise, executive-level email to project stakeholders summarizing sprint velocity, core accomplishments, zero blocking blockers, and next week\'s targets.',
    icon: 'mail',
  },
];

export const INITIAL_CHAT_SESSIONS = [
  {
    id: 'chat-1',
    title: 'Create a detailed 7-day sprint plan for...',
    createdAt: Date.now() - 3600000 * 2,
    updatedAt: Date.now() - 3600000 * 2,
    group: 'Today',
    messages: [
      {
        id: 'm1',
        role: 'user' as const,
        content: 'Create a detailed 7-day sprint plan for our product milestone release.',
        timestamp: Date.now() - 3600000 * 2,
      },
      {
        id: 'm2',
        role: 'assistant' as const,
        content: `### 🚀 7-Day Sprint Plan: Product Milestone Release\n\nHere is your high-velocity sprint breakdown:\n\n- **Day 1: Scope Freeze & Architecture Review** — Finalize API schemas, lock feature requirements, and establish CI/CD verification.\n- **Day 2-3: Core Module Implementation** — Implement state containers, integrate Memo API memory cache, and link realtime database endpoints.\n- **Day 4: Deep Reasoning & Edge-Case Testing** — Execute stress tests on vision upload pipelines, test offline sync, and audit admin authentication security.\n- **Day 5: Responsive UX Polish** — Verify fluid layout across mobile, tablet, and desktop viewports.\n- **Day 6: Staging Deployment & Telemetry** — Deploy backend on Render, deploy frontend on Vercel, and configure production environment secrets.\n- **Day 7: Launch & Monitoring** — Monitor error logs and track user satisfaction metrics.`,
        timestamp: Date.now() - 3600000 * 2 + 1000,
        modelUsed: 'AICredits',
      },
    ],
  },
  {
    id: 'chat-2',
    title: 'Draft a concise email to stakeholder...',
    createdAt: Date.now() - 3600000 * 5,
    updatedAt: Date.now() - 3600000 * 5,
    group: 'Today',
    messages: [],
  },
  {
    id: 'chat-3',
    title: "Analyze the 'Eisenhower Matrix' an...",
    createdAt: Date.now() - 3600000 * 8,
    updatedAt: Date.now() - 3600000 * 8,
    group: 'Today',
    messages: [],
  },
  {
    id: 'chat-4',
    title: 'Summarize the main differences be...',
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
    group: 'Yesterday',
    messages: [],
  },
  {
    id: 'chat-5',
    title: 'I need to negotiate an extension for ...',
    createdAt: Date.now() - 86400000 * 1.5,
    updatedAt: Date.now() - 86400000 * 1.5,
    group: 'Yesterday',
    messages: [],
  },
  {
    id: 'chat-6',
    title: 'Generate 5 effective morning habits...',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
    group: '7 days',
    messages: [],
  },
  {
    id: 'chat-7',
    title: 'As a non-technical PM, list 5 crucial...',
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
    group: '7 days',
    messages: [],
  },
  {
    id: 'chat-8',
    title: 'Help me allocate 8 hours tomorrow...',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
    group: '7 days',
    messages: [],
  },
  {
    id: 'chat-9',
    title: 'We need a creative name for our ne...',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 6,
    group: '7 days',
    messages: [],
  },
  {
    id: 'chat-10',
    title: 'Write a 100-word positive feedback...',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 7,
    group: '7 days',
    messages: [],
  },
];
